---
abstract: 'Perl module for structured errors. HTMLCustomPage version.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-Tags-HTMLCustomPage
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure::Die: 0.05
  Error::Pure::Utils: 0.05
  Exporter: 0
  HTTP::Headers::Fast: 0
  Indent::PerlStruct: 0.01
  List::MoreUtils: 0
  Readonly: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository:
    type: git
    url: git://github.com/tupinek/Error-Pure-Tags-HTMLCustomPage
    web: https://github.com/tupinek/Error-Pure-Tags-HTMLCustomPage
version: 0.01
