---
abstract: 'Perl module for structured errors. HTMLCustomPage version.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-Tags-HTMLCustomPage
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure::Die: 0.05
  Error::Pure::Utils: 0.05
  Exporter: 0
  HTTP::Headers::Fast: 0
  Indent::PerlStruct: 0.01
  List::MoreUtils: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-Tags-HTMLCustomPage
  homepage: https://github.com/tupinek/Error-Pure-Tags-HTMLCustomPage
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Error-Pure-Tags-HTMLCustomPage
version: 0.01
